name = "mm"
license = "MIT"
licenselink = "https://github.com/MaxMilton/hugo-theme-mm/blob/master/LICENSE"
description = ""
homepage = "https://github.com/MaxMilton/hugo-theme-mm"
tags = []
features = []
min_version = "0.41"

[author]
  name = "Max Milton"
  homepage = "https://maxmilton.com"
